language: rust
sudo: false
rust:
- stable
- beta
script:
- cargo test --verbose
- cargo test --no-default-features --verbose
matrix:
    include:
    - rust: nightly
      after_script: cargo bench --verbose
