language: rust
sudo: false
rust:
- stable
- beta
- 1.20.0
script:
- cargo build --verbose
- cargo test --verbose
- cargo build --features "serde-1-std" --verbose
- cargo test --features "serde-1-std" --verbose
matrix:
    include:
    - rust: nightly
      script:
      - cargo build --verbose
      - cargo test --verbose
      - cargo build --no-default-features --verbose
      - cargo test --no-default-features --verbose
      - cargo build --no-default-features --features "serde-1" --verbose
      - cargo test --no-default-features --features "serde-1" --verbose
      after_script: cargo bench --verbose
