[package]
name = "throw"
version = "0.1.2-dev"
authors = ["Dabo Ross <daboross@daboross.net>"]
description = "Throw is an extension of error handling in rust which adds statically produced stack traces"

documentation = "https://dabo.guru/rust/throw/"
repository = "https://github.com/daboross/rust-throw/"

readme = "README.md"
keywords = ["throw", "error", "catch", "result"]
license = "MIT"

[dev-dependencies]
regex = "0.2"
